/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Java_Swift_Prac;

import javax.swing.*;


public class App extends JFrame{
    public void Window(){
      JFrame f = new JFrame();
      JButton b = new JButton("click");

      b.setBounds(130, 100, 100, 40);
      f.add(b);

    }

    public static void main(String[] args) {
        App test = new App();
        test.setVisible(true);
        test.setSize(400, 300);
        test.set
    }
}
