/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Assignment1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

//Imports for API Tests
import java.lang.*;
import java.io.IOException;
import java.math.BigDecimal;

class Api_Tests {

  //Tests that the function returns the rates with the correct base
  @Test
  public void testGetRates() {
    try {
      App test = new App();
      String output = test.getRates("AUD");
      String base = output.substring(output.indexOf("\"b"), output.indexOf("\"b") + 12);

      assertNotEquals(output, "GET DIDN'T WORK");
      assertNotNull(output);
      assertEquals(base, "\"base\":\"AUD\"");
    } catch(IOException e) {
      System.out.println(e);
    }

  }

  //Test findRate finds a rate and that it is the corresponding rate
  @Tests
  public void testFindRate() {
    try {
      App test = new App();
      double usd = test.findRate("AUD", "USD");
      assertNotEquals(usd, -1);

      String str_rate = Double.stringOf(usd);
      String currency = output.substring(output.indexOf(str_rate) - 5, output.indexOf(str_rate) - 2);
      assertEquals(currency, "USD");
    } catch(IOException e) {
      System.out.println(e);
    }
  }

  //Test calculator produces conversion to two decimal places
  @Test
  public void testCalculator() {
    try {
      App test = new App();
      double conversion = test.calculator("AUD", "USD", 100);
      assertEquals(conversion, 71.65);
      assertFalse(BigDecimal.valueOf(conversion).scale() > 2);
    } catch (IOException e) {
      System.out.println(e);
    }
  }
}
