/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JUnit_Test;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
  //remove this default test method and include the one below
  //the above is how to fail a test. remove the code to have your tests passing

  //include this below test case
  @Test
  void testAdd() {
      App test = new App();
      int output = test.add(1, 2);
      //test.add where add is the method created in the JUnitDemo class
      assertEquals(3, output);
  }

  @Test
  void testSubtract() {
    App test = new App();
    int output = test.subtract(3,2);
    assertEquals(1, output);
  }

  @Test
  void testMultiply() {
    App test = new App();
    int output = test.multiply(3,2);
    assertEquals(6, output);
  }

  @Test
  void testDivision() {
    App test = new App();
    int output = test.division(4,2);
    assertEquals(2, output);
  }

  @Test
  void testSquare() {
    App test = new App();
    int output = test.square(5);
    assertEquals(25, output);
  }

  @Test
  void testIsOdd() {
    App test = new App();
    boolean output = test.isOddNumber(3);
    assertTrue(output);
  }

  @Test
  void testIsEven() {
    App test = new App();
    boolean output = test.isOddNumber(2);
    assertFalse(output);
  }


  @Test
  void testSetText() {
    App test = new App();
    String output = test.setText("hello world");
    assertSame("hello world", output);
  }

  @Test
  void testSetList() {
    App test = new App();
    List<String> output = test.setList("a", "b", "c");
    assertNotNull(output, "Not null");
  }
}
