/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JUnit_Test;

import java.util.Arrays;
import java.util.List;

public class App {
  public int add (int a, int b) {
       return a + b;
  }

  public int subtract (int a, int b) {
       return a - b;
  }

  public int multiply (int a, int b) {
       return a * b;
  }

  public int division (int a, int b) {
       return a/b;
  }

  public int square (int a) {
       return a * a;
  }

  public boolean isOddNumber (int a) {
       if (a%2 == 1) {
     return true;
 } else {
     return false;
 }
  }

  public String setText (String a) {
       return a;
  }

  public List<String> setList (String a, String b, String c) {
       List<String> arraylist = Arrays.asList(a, b, c);
       return arraylist;
  }

    public static void main(String[] args) {
        //System.out.println(new App().add(1,2));
        System.out.println("sucks to suck");
    }
}
